name: "修复测试用例"
description: "提交一个测试用例的修复"
title: "[TestCase Bug] "
labels: ["TestCase Fix / 测试用例修复"]

body:
  - type: markdown
    attributes:
      value: 欢迎为 mugen-riscv 提出新的 Pull Request！烦请填写以下表单：
  - type: input
    id: testcaseURL
    attributes:
      label: 测试用例路径
      description: 请填写测试用例路径
      placeholder: "e.g. testcases\\cli-test\\abrt\\oe_test_service_abrtd.sh"
    validations:
      required: true
  - type: input
    id: packagename
    attributes:
      label: 包名
      description: 请填写包名，如果这个软件包的所有测试套均未测试，则下列框无需填写。
      placeholder: "e.g. watchdog"
    validations:
      required: true
  - type: input
    id: testsuitname
    attributes:
      label: 测试套名称
      description: 请填写测试套名称
      placeholder: "e.g. cli-test"
    validations:
      required: false
  - type: input
    id: testcasename
    attributes:
      label: 测试用例名称
      description: 测试用例名称
      placeholder: "e.g. watchdog"
    validations:
      required: false
  - type: textarea
    id: expect
    attributes:
      label: 修复的问题（可以写 Issue 编号）
      placeholder: #1
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 日志
      description: 请直接粘贴你的日志，GitHub 将自动格式化输出
      render: shell
  - type: textarea
    id: othors
    attributes:
      label: 其他有助于解决该问题的内容
      description: 如果你了解相关的其他信息，请在此处报告
  - type: checkboxes
    id: terms
    attributes:
      label: 签署 [Code of Conduct](https://clasign.osinfra.cn/sign/Z2l0ZWUlMkZvcGVuZXVsZXI=)
      description: 提交本 Pull Request 需要签署开源贡献协议
      options:
        - label: 我同意在本项目中执行上述协议
          required: true
        - label: 我已经签署协议
          required: true